name: BuildProtect
version: 2.0
main: Its123Miguel321\BuildProtect\BuildProtect
api: 4.0.0
author: 'Its123Miguel321'

permissions:
  buildprotect.commands:
    default: op
  buildprotect.bypass:
    default: op