name: BuildProtect
main: Its123Miguel321\BuildProtect\BuildProtect
api: [3.0.0]
version: 1.0
author: Its123Miguel321

permissions:
 buildprotect.plugin:
  default: op
  children:
   buildprotect.wand:
    default: op
   buildprotect.save:
    default: op
   buildprotect.edit:
    default: op
   buildprotect.delete:
    default: op
   buildprotect.bypass:
    default: op
   buildprotect.admin:
    default: op
