# ================================================================================
#  ____            _   _       _  ____                   _                   _    
# | __ )   _   _  (_) | |   __| ||  _ \   _ __    ___   | |_    ___    ___  | |_  
# |  _ \  | | | | | | | |  / _` || |_) | | '__|  / _ \  | __|  / _ \  / __| | __| 
# | |_) | | |_| | | | | | | (_| ||  __/  | |    | (_) | | |_  |  __/ | (__  | |_  
# |____/   \__,_| |_| |_|  \__,_||_|     |_|     \___/   \__|  \___|  \___|  \__|
# made by Its123Miguel321

# ================================================================================

# Add the item ID you would to have as your wand! It has to be formatted as "1:0"
ItemID: "288:0"

# This is for what you would like to name the wand!
WandName: "§l§6Protection §fFeather"

# Set to false if you wouldn't like a message to send when an action is disabled. (BlockBreaking, BlockPlacing, PvP, Flight)
AreaMessages: true

# Message for block breaking being disabled.
BreakingDisabled: "§cYou can not break blocks here!"
# Message for block placing being disabled.
PlacingDisabled: "§cYou can not place blocks here!"
# Message for PvP being disabled.
AttackingDisabled: "§cYou can not hit another player here!"
# Message for Flight being disabled.
FlyingDisabled: "§cYou can not fly in this area!"
